#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nnn
Version  : 3.0
Release  : 2
URL      : https://github.com/jarun/nnn/releases/download/v3.0/nnn-v3.0.tar.gz
Source0  : https://github.com/jarun/nnn/releases/download/v3.0/nnn-v3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: nnn-bin = %{version}-%{release}
Requires: nnn-license = %{version}-%{release}
Requires: nnn-man = %{version}-%{release}
BuildRequires : pkgconfig(ncurses)
BuildRequires : readline-dev

%description
<h1 align="center">nnn - <i>supercharge your productivity!</i></h1>
<p align="center">
<a href="https://github.com/jarun/nnn/releases/latest"><img src="https://img.shields.io/github/release/jarun/nnn.svg?maxAge=600" alt="Latest release" /></a>
<a href="https://repology.org/project/nnn/versions"><img src="https://repology.org/badge/tiny-repos/nnn.svg" alt="Availability"></a>
<a href="https://travis-ci.org/jarun/nnn"><img src="https://img.shields.io/travis/jarun/nnn/master.svg?label=travis" alt="Travis Status" /></a>
<a href="https://circleci.com/gh/jarun/workflows/nnn"><img src="https://img.shields.io/circleci/project/github/jarun/nnn.svg?label=circleci" alt="CircleCI Status" /></a>
<a href="https://en.wikipedia.org/wiki/Privacy-invasive_software"><img src="https://img.shields.io/badge/privacy-✓-crimson" alt="Privacy Awareness" /></a>
<a href="https://github.com/jarun/nnn/blob/master/LICENSE"><img src="https://img.shields.io/badge/license-BSD%202--Clause-yellow.svg?maxAge=2592000" alt="License" /></a>
</p>

%package bin
Summary: bin components for the nnn package.
Group: Binaries
Requires: nnn-license = %{version}-%{release}

%description bin
bin components for the nnn package.


%package license
Summary: license components for the nnn package.
Group: Default

%description license
license components for the nnn package.


%package man
Summary: man components for the nnn package.
Group: Default

%description man
man components for the nnn package.


%prep
%setup -q -n nnn-3.0
cd %{_builddir}/nnn-3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582676249
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1582676249
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nnn
cp %{_builddir}/nnn-3.0/LICENSE %{buildroot}/usr/share/package-licenses/nnn/5e672bd0afe14541e924ae2664a83ed67aa0b504
%make_install PREFIX=/usr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nnn

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nnn/5e672bd0afe14541e924ae2664a83ed67aa0b504

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nnn.1
